name = "Paczka"
author = "ewvbm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e9a208e3406083eba3e3fe20620419c02eca90f9def6abc83675709242be181"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["forge"]
